# ##
# WARNING: absolute use space instead of tab to indent file.
# ##

# company or user name
author: "XtrmAddons"

# reference site
url: "https://www.xtrmaddons.com"

# generic title.
title: XtrmAddons WordPress Widget To Top

# generic description.
description: XtrmAddons WordPress Widget To Top github documentation.

# generic assets link root.
assets: "https://github.assets.xtrmaddons.com"

# pages collection
# see : https://jekyllrb.com/docs/collections/
collections_dir: "docs"



# "true" or "false" to show page header.
show_page_header: false

# "true" or "false" to indicate whether to provide a download URL
show_downloads: true

# show main navigation bar.
show_navbar: true

# navbar brand type: [icon|img]
navbar_brand_type: "img"

# navbar brand icon
navbar_brand_icon: "glyphicon-home"

# navbar brand image
navbar_brand_img: "https://github.assets.xtrmaddons.com/assets/images/logo.png"

# navbar brand title
navbar_brand_title: ""

# navbar brand date start
navbar_brand:
  date_start: "2007"
  date_end: "2019"

# navbar brand date end
navbar_brand_date_end: "2019"

# Your Google Analytics tracking ID
google_analytics: "UA-107731670-1"

google_adsense_client: "ca-pub-1175089473544116"
google_adsense_slot: "6837462325"
google_adsense_format: "auto"