# ##
# WARNING: absolute use space instead of tab to indent file.
# ##

# company or user name
author: "XtrmAddons"

# reference site
url: "https://www.xtrmaddons.com"
git_url: "https://github.wp-widget-to-top.xtrmaddons.com"

# generic title.
title: XtrmAddons WordPress Widget To Top

# generic description.
description: XtrmAddons WordPress Widget To Top github documentation.

# generic assets link root.
assets: "https://github.assets.xtrmaddons.com"

# pages collection
# see : https://jekyllrb.com/docs/collections/
collections_dir: "docs"

# navbar brand type: [icon|img]
navbar_brand_type: "img"

# navbar brand icon
navbar_brand_icon: "glyphicon-home"

# navbar brand image
navbar_brand_img: "https://github.assets.xtrmaddons.com/assets/images/logo.png"

# navbar brand title
navbar_brand_title: ""

# navbar brand
brand:
  copyright:
    date_start: "2007"
    date_end: "2019"

# navbar brand date end
# avbar_brand_date_end: "2019"

# Your Google Analytics tracking ID
google_analytics: "UA-107731670-1"

google_adsense_client: "ca-pub-1175089473544116"
google_adsense_slot: "6837462325"
google_adsense_format: "auto"